name: Compile script
on: 
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: 1.0.0
        required: true
env:
  KEYVAULT_NAME_DEV: dev
  KEYVAULT_NAME_PRE: pre
  KEYVAULT_NAME_PRO: pro
  
  SQLSCRIPTS: './sqlscripts/${{ github.event.inputs.version }}/'
  
jobs:
  compile-mvn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
        
      - uses: actions/github-script@v6
        id: assign-keyvault
        with:
          script: |
            const { KEYVAULT_NAME_DEV, KEYVAULT_NAME_PRE, KEYVAULT_NAME_PRO } = process.env;
            let keyVaultName = KEYVAULT_NAME_PRO;
            return keyVaultName;
          result-encoding: string

      - name: Get result
        run: echo "${{steps.assign-keyvault.outputs.result}}"
        
      - name: echo Scripts
        run: echo "releasedb Upgrade ${SQLSCRIPTS}"
